name: Cached Supabase CLI example workflow

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Supabase CLI version to use
        required: true
        default: "1.3.0"
      architecture:
        type: string
        description: Binary architecture
        default: amd64
        required: false
      image-registry:
        type: string
        description: Image registry
        default: ghcr.io
        required: false
      enable-binary-cache:
        type: boolean
        description: Use actions/cache for caching the supabase binary
        default: true
        required: false
      enable-docker-cache:
        type: boolean
        description: Use actions/cache for caching downloaded docker images
        default: false
        required: false

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Supabase CLI
        uses: bickoSiTiEff/setup-supabase-action@main
        with:
          version: ${{ inputs.version }}
          architecture: ${{ inputs.architecture }}
          image-registry: ${{ inputs.image-registry }}
          enable-binary-cache: ${{ inputs.enable-binary-cache }}
          enable-docker-cache: ${{ inputs.enable-docker-cache }}
      - name: Initialize new project
        run: supabase init
      - name: Start project
        run: supabase start
      - name: Stop project
        run: supabase stop
